[package]
authors = ["Sybrand Aarnoutse (syberant)"]
edition = "2018"
license = "MIT"
name = "evolvim-lib"
version = "0.2.0"

[dependencies]
bincode = "1.1.1"
noise = "0.5.1"
rand = "0.6.5"
serde = "1.0.87"
serde_derive = "1.0.87"

[dependencies.nalgebra]
features = ["serde-serialize"]
version = "0.17.0"

[dependencies.rayon]
optional = true
version = "1.0.3"

# Enable wasm-bindgen feature of rand when targetting wasm.
[target.'cfg(target_arch = "wasm32")'.dependencies.rand]
# TODO: package version should ideally not have to be repeated.
version = "0.6.5"
features = ["wasm-bindgen"]

[features]
bench = []
multithreading = ["rayon"]

[lib]
name = "lib_evolvim"
path = "./src/lib/mod.rs"